version: '3.9'
services:
    ptgen:
        image: 'ghcr.io/sanzuwu/pt-gen'
        volumes:
            - './env:/app/pt-gen-universal/.env'
        restart: always
        hostname: pt-gen
        container_name: pt-gen
        environment:
            - TZ=Asia/Shanghai
            - PGID=1000
            - PUID=1000
        tty: true
        stdin_open: true
        network_mode: host
